export { default as authApi } from "./auth.api";
export { default as userApi } from "./user.api";
export { default as studentApi } from "./student.api";
export { default as categoryClusterApi } from "./category-cluster.api";
export { default as categoryApi } from "./category.api";
export { default as courseApi } from "./course.api";
export { default as lecturerApi } from "./lecturer.api";
export { default as favoriteApi } from "./favorite.api";
export { default as homeApi } from "./home.api";